/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksIdIndexRouteImport } from './routes/tasks/$id/index'
import { Route as TasksIdEditRouteImport } from './routes/tasks/$id/edit'

const TasksIndexLazyRouteImport = createFileRoute('/tasks/')()

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexLazyRoute = TasksIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any).lazy(() => import('./routes/tasks/index.lazy').then((d) => d.Route))
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TasksRoute,
} as any)
const TasksIdIndexRoute = TasksIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/': typeof TasksIndexLazyRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/tasks/$id': typeof TasksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks': typeof TasksIndexLazyRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/tasks/$id': typeof TasksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/': typeof TasksIndexLazyRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/tasks'
    | '/tasks/new'
    | '/tasks/'
    | '/tasks/$id/edit'
    | '/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/tasks/new'
    | '/tasks'
    | '/tasks/$id/edit'
    | '/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/tasks'
    | '/tasks/new'
    | '/tasks/'
    | '/tasks/$id/edit'
    | '/tasks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexLazyRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/$id/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface TasksRouteChildren {
  TasksNewRoute: typeof TasksNewRoute
  TasksIndexLazyRoute: typeof TasksIndexLazyRoute
  TasksIdEditRoute: typeof TasksIdEditRoute
  TasksIdIndexRoute: typeof TasksIdIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksNewRoute: TasksNewRoute,
  TasksIndexLazyRoute: TasksIndexLazyRoute,
  TasksIdEditRoute: TasksIdEditRoute,
  TasksIdIndexRoute: TasksIdIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
